import React from 'react';
import { MarketingPageTemplate } from '../components/ui/MarketingPageTemplate';
import { Section, Card, InlineCTA } from '../components/ui/Components';
import { Shield, Lock, Brain, Activity, LineChart, Lightbulb } from 'lucide-react';
import { AlertBanner } from '../components/ui/Components';

export const About: React.FC = () => {
  return (
    <MarketingPageTemplate
      title="About SomnoAI Digital Sleep Lab"
      subtitle="SomnoAI Digital Sleep Lab is a research-driven technology initiative dedicated to exploring how artificial intelligence and advanced data analysis can deepen the understanding of human sleep."
      ctaPrimary={{ text: "Explore Platform", link: "/product" }}
      ctaSecondary={{ text: "Read Research", link: "/research" }}
    >
      <Section title="Our Mission">
        <p className="text-xl text-slate-300 leading-relaxed max-w-4xl">
          The project investigates how digital signals generated by everyday devices can be transformed into meaningful insights about rest, recovery, and behavioral rhythms. By combining curiosity, scientific inquiry, and technological innovation, SomnoAI Digital Sleep Lab seeks to make sleep knowledge more accessible and understandable for the modern digital world.
        </p>
      </Section>

      <Section title="Guiding Principles">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card 
            title="Transparency" 
            description="We aim to create tools that are accessible and understandable, ensuring users know exactly how their data is being used and analyzed."
            icon={<Shield />}
          />
          <Card 
            title="Privacy" 
            description="Data is treated as a sensitive resource that must be handled responsibly and with respect for users. We maintain strong commitments to ethical data practices."
            icon={<Lock />}
          />
          <Card 
            title="Responsible AI" 
            description="We build analytical frameworks that reveal patterns hidden within large volumes of behavioral data, always prioritizing interpretability and scientific integrity."
            icon={<Brain />}
          />
        </div>
      </Section>

      <Section title="What We Do">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative">
          <div className="hidden md:block absolute top-1/2 left-0 w-full h-0.5 bg-gradient-to-r from-indigo-500/0 via-indigo-500/20 to-indigo-500/0 -translate-y-1/2 -z-10" />
          <Card 
            title="Data Collection" 
            description="Modern wearable devices and digital health platforms generate large amounts of physiological and behavioral data."
            icon={<Activity />}
            className="bg-[#01040a] relative z-10"
          />
          <Card 
            title="Computational Analysis" 
            description="We apply computational models, statistical analysis, and machine learning techniques to analyze sleep-related data."
            icon={<LineChart />}
            className="bg-[#01040a] relative z-10"
          />
          <Card 
            title="Meaningful Insights" 
            description="We transform raw signals into structured information that individuals can understand, exploring long-term behavioral trends."
            icon={<Lightbulb />}
            className="bg-[#01040a] relative z-10"
          />
        </div>
      </Section>

      <Section>
        <AlertBanner title="Medical Disclaimer" type="warning">
          SomnoAI Digital Sleep Lab operates as a research-oriented informational platform. It does not provide medical advice, diagnosis, or treatment. Instead, the platform is designed to help users better understand behavioral trends associated with rest and recovery.
        </AlertBanner>
      </Section>

      <div className="text-center pt-12 border-t border-white/5">
        <h3 className="text-2xl font-bold text-white mb-6">Interested in our work?</h3>
        <div className="flex items-center justify-center gap-6">
          <InlineCTA text="Contact Us" link="/contact" />
          <span className="text-white/20">|</span>
          <InlineCTA text="Collaboration" link="/contact" />
        </div>
      </div>
    </MarketingPageTemplate>
  );
};
