import React from 'react';
import { MarketingPageTemplate } from '../components/ui/MarketingPageTemplate';
import { Section, Card, InlineCTA } from '../components/ui/Components';
import { Shield, Lock, Brain, Activity, LineChart, Lightbulb } from 'lucide-react';
import { AlertBanner } from '../components/ui/Components';
import { Language, getTranslation } from '../services/i18n';

interface AboutProps {
  lang: Language;
}

export const About: React.FC<AboutProps> = ({ lang }) => {
  const t = getTranslation(lang, 'about');
  const lt = getTranslation(lang, 'landing');

  return (
    <MarketingPageTemplate
      title={lang === 'zh' ? "关于 Digital Sleep Lab" : "About Digital Sleep Lab"}
      subtitle={lang === 'zh' ? "Digital Sleep Lab 是一个以研究为导向的技术项目，致力于探索人工智能和先进数据分析如何加深对人类睡眠的理解。" : "Digital Sleep Lab is a research-driven technology initiative dedicated to exploring how artificial intelligence and advanced data analysis can deepen the understanding of human sleep."}
      ctaPrimary={{ text: lt.ctaPrimary || "Explore Platform", link: "/product" }}
      ctaSecondary={{ text: lang === 'zh' ? "阅读研究" : "Read Research", link: "/research" }}
    >
      <Section title={lang === 'zh' ? "我们的使命" : "Our Mission"}>
        <p className="text-xl text-slate-300 leading-relaxed max-w-4xl">
          {lt.footer?.mission || "The project investigates how digital signals generated by everyday devices can be transformed into meaningful insights about rest, recovery, and behavioral rhythms. By combining curiosity, scientific inquiry, and technological innovation, Digital Sleep Lab seeks to make sleep knowledge more accessible and understandable for the modern digital world."}
        </p>
      </Section>

      <Section title={lang === 'zh' ? "指导原则" : "Guiding Principles"}>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          <Card 
            title={lang === 'zh' ? "透明度" : "Transparency"} 
            description={lang === 'zh' ? "我们致力于创建易于访问且易于理解的工具，确保用户确切了解其数据的使用和分析方式。" : "We aim to create tools that are accessible and understandable, ensuring users know exactly how their data is being used and analyzed."}
            icon={<Shield />}
          />
          <Card 
            title={lang === 'zh' ? "隐私" : "Privacy"} 
            description={lang === 'zh' ? "数据被视为敏感资源，必须以负责任且尊重用户的方式处理。我们对道德数据实践有着坚定的承诺。" : "Data is treated as a sensitive resource that must be handled responsibly and with respect for users. We maintain strong commitments to ethical data practices."}
            icon={<Lock />}
          />
          <Card 
            title={lang === 'zh' ? "负责任的 AI" : "Responsible AI"} 
            description={lang === 'zh' ? "我们构建分析框架，揭示隐藏在大量行为数据中的模式，始终优先考虑可解释性和科学完整性。" : "We build analytical frameworks that reveal patterns hidden within large volumes of behavioral data, always prioritizing interpretability and scientific integrity."}
            icon={<Brain />}
          />
        </div>
      </Section>

      <Section title={lang === 'zh' ? "我们做什么" : "What We Do"}>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 relative">
          <div className="hidden md:block absolute top-1/2 left-0 w-full h-0.5 bg-gradient-to-r from-indigo-500/0 via-indigo-500/20 to-indigo-500/0 -translate-y-1/2 -z-10" />
          <Card 
            title={lang === 'zh' ? "数据采集" : "Data Collection"} 
            description={lang === 'zh' ? "现代可穿戴设备和数字健康平台产生大量的生理和行为数据。" : "Modern wearable devices and digital health platforms generate large amounts of physiological and behavioral data."}
            icon={<Activity />}
            className="bg-[#01040a] relative z-10"
          />
          <Card 
            title={lang === 'zh' ? "计算分析" : "Computational Analysis"} 
            description={lang === 'zh' ? "我们应用计算模型、统计分析和机器学习技术来分析与睡眠相关的数据。" : "We apply computational models, statistical analysis, and machine learning techniques to analyze sleep-related data."}
            icon={<LineChart />}
            className="bg-[#01040a] relative z-10"
          />
          <Card 
            title={lang === 'zh' ? "有意义的洞察" : "Meaningful Insights"} 
            description={lang === 'zh' ? "我们将原始信号转化为结构化信息，使个人能够理解，并探索长期的行为趋势。" : "We transform raw signals into structured information that individuals can understand, exploring long-term behavioral trends."}
            icon={<Lightbulb />}
            className="bg-[#01040a] relative z-10"
          />
        </div>
      </Section>

      <Section>
        <AlertBanner title={lang === 'zh' ? "医疗免责声明" : "Medical Disclaimer"} type="warning">
          {lang === 'zh' ? "Digital Sleep Lab 作为一个以研究为导向的信息平台运行。它不提供医疗建议、诊断或治疗。相反，该平台旨在帮助用户更好地了解与休息和恢复相关的行为趋势。" : "Digital Sleep Lab operates as a research-oriented informational platform. It does not provide medical advice, diagnosis, or treatment. Instead, the platform is designed to help users better understand behavioral trends associated with rest and recovery."}
        </AlertBanner>
      </Section>

      <div className="text-center pt-12 border-t border-white/5">
        <h3 className="text-2xl font-bold text-white mb-6">{lang === 'zh' ? "对我们的工作感兴趣？" : "Interested in our work?"}</h3>
        <div className="flex items-center justify-center gap-6">
          <InlineCTA text={lang === 'zh' ? "联系我们" : "Contact Us"} link="/contact" />
          <span className="text-white/20">|</span>
          <InlineCTA text={lang === 'zh' ? "合作洽谈" : "Collaboration"} link="/contact" />
        </div>
      </div>
    </MarketingPageTemplate>
  );
};
