import React from 'react';
import { MarketingPageTemplate } from '../components/ui/MarketingPageTemplate';
import { Section, Card, InlineCTA } from '../components/ui/Components';
import { Quote, Linkedin, Github, Twitter } from 'lucide-react';

export const Founder: React.FC = () => {
  return (
    <MarketingPageTemplate
      title="Meet the Founder"
      subtitle="The vision behind SomnoAI Digital Sleep Lab and our commitment to advancing sleep science through technology."
    >
      <Section>
        <div className="flex flex-col md:flex-row gap-12 items-center">
          <div className="w-full md:w-1/3">
            <div className="aspect-square rounded-3xl overflow-hidden bg-slate-900 border border-white/10 relative group">
              <img 
                src="https://picsum.photos/seed/founder/800/800" 
                alt="Founder" 
                className="w-full h-full object-cover grayscale group-hover:grayscale-0 transition-all duration-500"
                referrerPolicy="no-referrer"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-[#01040a] via-transparent to-transparent opacity-60" />
            </div>
          </div>
          <div className="w-full md:w-2/3 space-y-6">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-indigo-500/10 border border-indigo-500/20 text-indigo-400 text-xs font-bold uppercase tracking-widest">
              Founder & Lead Researcher
            </div>
            <h2 className="text-4xl font-bold text-white">Vyncus Lim</h2>
            <div className="flex items-center gap-4 text-slate-400">
              <a href="#" className="hover:text-white transition-colors"><Linkedin size={20} /></a>
              <a href="#" className="hover:text-white transition-colors"><Github size={20} /></a>
              <a href="#" className="hover:text-white transition-colors"><Twitter size={20} /></a>
            </div>
            <div className="prose prose-invert max-w-none text-slate-300">
              <p className="text-lg leading-relaxed">
                Vyncus Lim is a technology researcher and developer with a deep interest in the intersection of human physiology and digital signals. With a background in data science and a passion for health optimization, Vyncus founded SomnoAI Digital Sleep Lab to explore how the data generated by our everyday devices can be used to improve our understanding of sleep.
              </p>
              <p className="text-lg leading-relaxed">
                "Sleep is one of the most fundamental yet least understood aspects of human health. Our goal is not just to track sleep, but to decode the behavioral patterns that define it, making that knowledge accessible to everyone."
              </p>
            </div>
          </div>
        </div>
      </Section>

      <Section title="The Vision">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="p-8 rounded-2xl bg-slate-900/50 border border-white/5 relative">
            <Quote className="absolute top-6 right-6 text-indigo-500/20" size={48} />
            <h3 className="text-xl font-bold text-white mb-4">Democratizing Sleep Science</h3>
            <p className="text-slate-400 leading-relaxed">
              We believe that high-quality sleep insights shouldn't be restricted to clinical settings. By leveraging consumer technology and advanced AI, we can bring sophisticated sleep analysis to the palm of your hand.
            </p>
          </div>
          <div className="p-8 rounded-2xl bg-slate-900/50 border border-white/5 relative">
            <Quote className="absolute top-6 right-6 text-indigo-500/20" size={48} />
            <h3 className="text-xl font-bold text-white mb-4">Ethical Data Practices</h3>
            <p className="text-slate-400 leading-relaxed">
              In an era of data exploitation, we stand for transparency and user ownership. Our commitment to privacy is not just a policy; it's a core design principle of everything we build.
            </p>
          </div>
        </div>
      </Section>

      <Section title="Key Milestones">
        <div className="space-y-6">
          <div className="flex gap-6">
            <div className="w-24 shrink-0 text-indigo-400 font-mono font-bold pt-1">2023 Q3</div>
            <div className="flex-grow pb-6 border-b border-white/5">
              <h4 className="text-white font-bold mb-2">Project Inception</h4>
              <p className="text-slate-400 text-sm">Initial research into actigraphy-based sleep modeling and data collection frameworks.</p>
            </div>
          </div>
          <div className="flex gap-6">
            <div className="w-24 shrink-0 text-indigo-400 font-mono font-bold pt-1">2023 Q4</div>
            <div className="flex-grow pb-6 border-b border-white/5">
              <h4 className="text-white font-bold mb-2">Alpha Prototype</h4>
              <p className="text-slate-400 text-sm">Development of the first computational engine capable of detecting sleep onset and offset trends.</p>
            </div>
          </div>
          <div className="flex gap-6">
            <div className="w-24 shrink-0 text-indigo-400 font-mono font-bold pt-1">2024 Q1</div>
            <div className="flex-grow pb-6 border-b border-white/5">
              <h4 className="text-white font-bold mb-2">SomnoAI Digital Sleep Lab Launch</h4>
              <p className="text-slate-400 text-sm">Official launch of the research platform and opening of the waitlist for early participants.</p>
            </div>
          </div>
        </div>
      </Section>

      <div className="text-center pt-12 border-t border-white/5">
        <InlineCTA text="Read our Mission" link="/about" />
      </div>
    </MarketingPageTemplate>
  );
};
