import React from 'react';
import { LegalPageTemplate } from '../components/ui/LegalPageTemplate';

export const HealthDisclaimer: React.FC = () => {
  return (
    <LegalPageTemplate
      title="Health & Medical Disclaimer"
      lastUpdated="March 19, 2026"
      breadcrumbs={[{ label: 'Legal', link: '/legal' }, { label: 'Health Disclaimer' }]}
    >
      <div className="text-slate-300 leading-relaxed space-y-6">
        <p>Welcome to SomnoAI Digital Sleep Lab.</p>
        <p>Please read this Health and Medical Disclaimer carefully before using our website, services, or products.</p>

        <h2 className="text-2xl font-black mt-12 mb-6 text-indigo-400 uppercase tracking-tight italic">1. Not Medical Advice</h2>
        <p>The information, insights, analytics, text, graphics, images, and other material provided by SomnoAI Digital Sleep Lab (collectively, the “Content”) are for informational, educational, and general wellness purposes only.</p>
        <p>We are not a healthcare provider, medical clinic, or diagnostic facility.</p>
        <p>The Content is not intended to be a substitute for professional medical advice, diagnosis, or treatment.</p>

        <h2 className="text-2xl font-black mt-12 mb-6 text-indigo-400 uppercase tracking-tight italic">2. No Doctor-Patient Relationship</h2>
        <p>Using our services, reading our Content, or interacting with our platform does not create a doctor-patient relationship, therapist-patient relationship, or any other healthcare professional relationship between you and SomnoAI Digital Sleep Lab.</p>

        <h2 className="text-2xl font-black mt-12 mb-6 text-indigo-400 uppercase tracking-tight italic">3. Consult Your Physician</h2>
        <p>Always seek the advice of your physician or other qualified health provider with any questions you may have regarding a medical condition, sleep disorder, or health objective.</p>
        <p>Never disregard professional medical advice or delay in seeking it because of something you have read on our website or inferred from our analytics.</p>
        <p>If you think you may have a medical emergency, call your doctor or emergency services immediately.</p>

        <h2 className="text-2xl font-black mt-12 mb-6 text-indigo-400 uppercase tracking-tight italic">4. Accuracy and Limitations of AI and Wearable Data</h2>
        <p>Our platform relies on data generated by third-party wearable devices, sensors, or user inputs, which are then analyzed using artificial intelligence and algorithms.</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>We do not guarantee the accuracy, completeness, or reliability of the data collected by third-party devices.</li>
          <li>AI-generated insights are probabilistic and may contain errors, false positives, or false negatives.</li>
          <li>Our analytics are designed to highlight patterns and trends for personal wellness and self-tracking, not to diagnose sleep apnea, insomnia, narcolepsy, or any other clinical sleep disorder.</li>
        </ul>

        <h2 className="text-2xl font-black mt-12 mb-6 text-indigo-400 uppercase tracking-tight italic">5. Assumption of Risk</h2>
        <p>Any reliance on the Content provided by SomnoAI Digital Sleep Lab is solely at your own risk.</p>
        <p>You are solely responsible for evaluating the insights provided and deciding whether to make lifestyle, behavioral, or wellness changes. We strongly recommend discussing any significant changes to your sleep habits, diet, or exercise routine with a qualified healthcare professional.</p>

        <h2 className="text-2xl font-black mt-12 mb-6 text-indigo-400 uppercase tracking-tight italic">6. No Endorsement</h2>
        <p>SomnoAI Digital Sleep Lab does not recommend or endorse any specific tests, physicians, products, procedures, opinions, or other information that may be mentioned on the website.</p>

        <h2 className="text-2xl font-black mt-12 mb-6 text-indigo-400 uppercase tracking-tight italic">7. Changes to This Disclaimer</h2>
        <p>We may update this Health and Medical Disclaimer from time to time. By continuing to use our services after updates are published, you agree to the revised terms.</p>
      </div>
    </LegalPageTemplate>
  );
};
